### ISSUE TITLE
ikchain bones not copied between survivors

### ISSUE THREAD

**Issue by ChimiChamo** [TwentyCat/l4d2_survivors_converter#2]
My model uses a different bone for the "rhand" ikchain but when compiling the new qcs made use the default right hand bone causing the compile to fail, the ik bones should be copied from the original qc into the new ones

**Comment by TwentyCat** [comment]
can you transfer your compiling files to me?

**Comment by ChimiChamo** [comment]
heres the google drive link for the worldmodel compiling files: https://drive.google.com/drive/folders/1wSSW8YGunLutI1kD_O9D_9rprR3ipo-n?usp=sharing

**Comment by TwentyCat** [comment]
> heres the google drive link for the worldmodel compiling files: https://drive.google.com/drive/folders/1wSSW8YGunLutI1kD_O9D_9rprR3ipo-n?usp=sharing

thank you. this program was designed to use specific QC template and didn't take this situation into consider, i will try to fix it :)

**Comment by TwentyCat** [comment]
updated, thanks for reporting this issue❤
